### ISSUE TITLE
bithermical heating

### ISSUE THREAD

**Issue by Yocee84** [Alexwijn/SAT#10]
Hi!

I congratulate this super project!

I need a little plus thing. One outside thermometer (ds18****) measure the temperature. When i set one value (0 celsius), below start gas boiler, above start Heatpump.
When the heat pump is working (switch.heatpump_on_off), the gas boiler should not (CS=0). Can this be solved?

**Comment by sergeantd83** [comment]
Hi Yocee,

You can create an automation to achieve this kind of control. You need to add a state trigger for you outside temperature sensor and leave it blank, so the automation will start again when you have an updated value of you OT sensor. Then you need to add a choose action. 1st option contition will be above 0 and as actions you can set the climate entities as you wish. The 2nd option condition will be when OT is below 0.1. Also you can add some time and create a schedule.

FYI SAT soon will support ON/OFF thermostats, this feature will be called ```PID Thermostat with PWM```. So you can create a new SAT climate entity that will control your heat pump.

**Comment by Yocee84** [comment]
I think I understand, or I will understand later.
Please help me some more.
I have 5 rooms. Each has a separate pump and thermometer. Do I have to set the SAT five times, one for each room?

**Comment by sergeantd83** [comment]
No, you need to add the temperature sensor of your main room ( E.g Living room ) as your SAT entity. The other four climate entities of the other rooms will be added in the areas tab as additional thermostats in the rooms section.
SAT will control the flow water temperature for your home based on your main room and at the same time will monitor if the room climates hvac_action is idle/heating or hvac_mode is off/heat. This will ensure that your pump ( heat pump or boiler ) will deliver heating only when it is needed.

**Comment by Yocee84** [comment]
Thanks. You can also change the water temperature of the heat pump via Modbus or your own integration, not just on/off. It's just an idea. For example, you can use the 'Template Climate' integration.

If this new version comes out, how might it affect bitermic switching? How will you handle multiple heat generators?

**Comment by sergeantd83** [comment]
That’s great news! @Alexwijn

**Comment by sergeantd83** [comment]
That’s great news! @Alexwijn did a wonderful job on this component and made it modular. Currently SAT supports OpenTherm ( MQTT/Serial ) connection and ON/OFF thermostats. If you want you can add the modbus connection option for this component. If you want to create this option please let us know since we don’t own a modbus pump and as a result it is impossible to create this type of connection.

**Comment by Yocee84** [comment]
I'm not smart enough for that. It's still great.
What do you think about multiple heat generators?

**Comment by sergeantd83** [comment]
Currently we can’t support it for many reasons. Our main focus now is to streamline the SAT experience. Maybe in the future we will support it. Currently you can use the automation described in my first post.
