### ISSUE TITLE
Configuration errors

### ISSUE THREAD

**Issue by gmeik** [Alexwijn/SAT#11]
An error pops up when clicking 'Configure' -> 'General'
![Screenshot_20231110_175353](https://github.com/Alexwijn/SAT/assets/123992613/cdb64d54-6884-4f77-a6be-7cfd8f4d1716)

I am using the latest SAT development version of 2023-11-09. Using Home Assistant 2022.10.5.

**Comment by Alexwijn** [comment]
You are required to have at least 2023.1 of Home Assistant installed.

**Comment by gmeik** [comment]
I upgraded to Home Assistant 2023.11.2. That solved this issue.
Now this error pops up
![Screenshot_20231110_182041](https://github.com/Alexwijn/SAT/assets/123992613/5884d1cb-c63f-4ab4-bcbf-e995b697484f)

**Comment by gmeik** [comment]
Integration was removed, re-added. Also SAT itself was removed and re-added (I run Home Assistant in a Docker container). The same error still occurs on the General configuration page. It seems an empty window_sensor is not accepted?
The thermostat works though, that's already a big step.

**Comment by Alexwijn** [comment]
Ah yes, totally forgot about that issue. It's basically a Home Assistant issue since for some reason I can't save "nothing" to the configuration.

**Comment by Alexwijn** [comment]
Try the latest version. Its support multiple contact sensors now, so that fixed the bug that was caused my Home Assistant itself.

**Comment by gmeik** [comment]
This solves the issue
