### ISSUE TITLE
Warming up state not turning off

### ISSUE THREAD

**Issue by ronaldt80** [Alexwijn/SAT#19]
This warming up state which is supposed to last 15 minutes is not turning off.. it's been at it for 40 minutes. 

As mentioned, this feature for my setup is more like a bug. The heatpump increases it's power very gradually. Adding 15 minutes serves no purpose , and it seems to be not limited to 15 minutes either.
![Screenshot_20231209-231800](https://github.com/Alexwijn/SAT/assets/53364332/6377b477-7614-4105-9208-fc51507ae2fe)

**Comment by Alexwijn** [comment]
Please share your current state.

**Comment by ronaldt80** [comment]
```
hvac_modes:
  - "off"
  - heat
min_temp: 7
max_temp: 35
target_temp_step: 0.5
preset_modes:
  - none
  - activity
  - away
  - home
  - sleep
  - comfort
current_temperature: 20.5
temperature: 21
current_humidity: 53
hvac_action: heating
preset_mode: comfort
error: 0.5
integral: 0
derivative: 0
proportional: 11.732
history_size: 2
collected_errors: 0
integral_enabled: false
pre_custom_temperature: 20.5
pre_activity_temperature: null
derivative_enabled: true
derivative_raw: 0
current_kp: 23.463
current_ki: 0.000321
current_kd: 42375.6
rooms:
  climate.radiator_sophia: 15
  climate.radiator_emilia: 15
  climate.radiator_attic_tvroom: 14
  climate.radiator_attic_guestroom: 14
  climate.bedroom: 17.5
setpoint: 35.4
summer_simmer_index: 23.3
summer_simmer_perception: Slightly Cool
warming_up_data:
  error: 0.8
  started: 3480996.650287125
warming_up_derivative: 74.39
valves_open: true
heating_curve: 23.7
minimum_setpoint: 28.6
requested_setpoint: 35.4
adjusted_minimum_setpoint: 28.6
outside_temperature: 9.8
optimal_coefficient: 1.8
coefficient_derivative: 0
relative_modulation_value: 0
relative_modulation_state: warming_up
relative_modulation_enabled: false
pulse_width_modulation_enabled: false
pulse_width_modulation_state: idle
pulse_width_modulation_duty_cycle: null
friendly_name: Living Room
supported_features: 17
```

**Comment by Alexwijn** [comment]
Correction, not sure how I came up with 15 minutes, but it's 3 minutes warming up.

Not sure why it keep getting stuck in warming up. I did not came across this issue just yet.

When was it the last time you changed preset / setpoint?

**Comment by ronaldt80** [comment]
Setpoint was stable for 24 hours. What helped in the end was increase the setpoint and lower it again.

There are also no logs to support this, just the mere fact that it was stuck at this state attribute. Also restarting HA, reloading the integration and even reinstalling it did not help. Ideally I would like to be able to turn this off completely as the "warmup" is native to the heatpump already 

By the way, what is pulse modulation?

**Comment by Alexwijn** [comment]
What type of heating system did you choice at the start, since a heat pump isn't listed?

**Comment by Alexwijn** [comment]
After some talks, I added support for a Heat Pump. Warming up is disabled when using that. I also changed the logic of how we calculate how long we are warming up.

The stamp wasn't accurate anymore if you reloaded or restarted, and since it restored the state it may take a very long three minutes to go off again.

**Comment by ronaldt80** [comment]
I used underfloor and changed the target temperature to 38. Will reinstall and select heatpump - curious if it works!

Otherwise I set it up with aggression level 2 and a heatcurve of 1.1. Today that works quite well. Still not completely sure what the output of the heatcurve refers to, it's now 23.2 whilst Ta is 31 - is there a relation?

**Comment by Alexwijn** [comment]
What do you mean with output of the `heatcuve`, are you reffering to the `heating_curve` attribute?

**Comment by ronaldt80** [comment]
Yes, indeed

**Comment by Alexwijn** [comment]
That's the ideal radiator temperature, where the house won't drop temperature nor would let it rise.

**Comment by ronaldt80** [comment]
With new heatpump setting this issue is gone
