### ISSUE TITLE
MQTT Option?

### ISSUE THREAD

**Issue by joeblack2k** [Alexwijn/SAT#24]
installed it, tried the beta and not the develop.. but i dont see an mqtt option?

<img width="577" alt="Screenshot 2024-01-05 at 21 10 50" src="https://github.com/Alexwijn/SAT/assets/3456102/2873a9d3-a575-403b-86ae-ff45474fa163">

**Comment by Alexwijn** [comment]
Make sure you have at least version 2023.5 of HA.

**Comment by joeblack2k** [comment]
Home Assistant is up to date updated it yesterday it’s running haos on a dell nothing fancy

**Comment by joeblack2k** [comment]
![IMG_2158](https://github.com/Alexwijn/SAT/assets/3456102/ab212aa3-e15a-40d2-8bbf-3ce5a19ab927)

**Comment by Alexwijn** [comment]
Just pushed out a new version that should fix the compatibility issue with Home Assistant 2024.1.x.

**Comment by joeblack2k** [comment]
Fixed! thanks
