### ISSUE TITLE
Best way to approach this house

### ISSUE THREAD

**Issue by joeblack2k** [Alexwijn/SAT#30]
I’am at a loss.. I can’t figure out what the best way is to approach my situation. Perhaps you have some insight.

currently:
Tado controled system with radiator plugs.
Floor heating downstairs. At the pump I have a tado installed so the valve can be closed.
Upper 2 rooms with tado radiator plugs and one room with airco heating.

1. Should I remove the tado radiator at the floorheating pump and just let it go ?

2. Should I remove all radiator plugs and get tuya plugs or some other non tado ones so that they don’t interfere with the boiler/thermostat

or can SAT work with everything tado?

I am at this for days now and I cannot figure out the right path forward

**Comment by joeblack2k** [comment]
I'm really grateful for your response.

Here's a detailed layout of my house:

Downstairs:

-     A Tado Thermostat mounted on the wall.
-     The underfloor heating pump is controlled by a Tado TRV (link to the image: https://imgur.com/a/8hYCXxD).
-     In our open kitchen, there's a radiator with a Tado TRV. However, I'm considering replacing this TRV with a standard thermostat knob since we never use the radiator.
-     The toilet has a radiator equipped with a Tado TRV.

Upstairs:

- 
-     Both kids' rooms have radiators with Tado TRVs.
-     The master bedroom has an LG Airco (controlled by Tado) and a radiator with a Tado TRV, which we never use. I'm thinking of replacing this TRV with a regular thermostat.
-     The bathroom is fitted with a Tado TRV.

In total, we currently have 7 Tado TRVs and one LG AC controlled by a Tado AC unit.

We prefer having a temperature of around 19/20°C downstairs and 18/19°C upstairs.

When setting up SAT, I used the temperature and humidity readings from the Tado thermostat to input the indoor temperature. I selected "rooms" and added the other TRVs (kids' rooms, bathroom, toilet, and bedroom).

Should I also include the main room, like the floor heating TRV, in this setup? Or is that managed by the OTGW? I assumed that most people don't have a TRV on their underfloor heating pump, which is why I wondered if I should remove it and just let the water flow freely.

**Comment by sergeantd83** [comment]
> A Tado Thermostat mounted on the wall.
The underfloor heating pump is controlled by a Tado TRV

I assume that your Thermostat is linked in the same room with the underfloor TRV, correct?
If this assumption is correct, then you should follow my first post and set the Atari thermostat 0.5 above SAT’s climate entity. This way you ensure that SAT will regulate the underfloor temperature.
**But** if you don’t have a pilot radiator ( radiator without TRV ) in your system, maybe it is better to remove this underfloor TRV completely and let SAT regulate the underfloor temperature
