### ISSUE TITLE
Unable to setup MQTT

### ISSUE THREAD

**Issue by hhoef** [Alexwijn/SAT#31]
I have OTmonitor publishing to /events/central_heating/otmonitor. 

When I try to setup SAT with MQTT gateway and I use otmonitor for the "top topic" I get "No matching devices fount" when selecting "Device".

HA core: 2024.1.2
HA superviser: 2023.12.0
OS: 11.3
Frontend: 20240104.0  
SAT version: 3.0.1
installed through: HACS

**Comment by Alexwijn** [comment]
You have to setup the MQTT integration and it has to find the device, so you can select it.

**Comment by hhoef** [comment]
I have MQTT setup in the integration.

**Comment by Alexwijn** [comment]
Alright, did it detected the OTGW device?

**Comment by Alexwijn** [comment]
I think I misread the first message. Do you use the Wi-Fi or the Ethernet version of OTGW?

**Comment by hhoef** [comment]
I use the otgw hardware from https://otgw.tclcode.com/. The gateway is connected via serial to a RPI that runs otmonitor (https://otgw.tclcode.com/otmonitor.html#configuration). Otmonitor is configured to use MQTT for publishing it's data.
HA runs on a different computer and I installed mosquitto MQTT integration on it. In configuration.yaml I added:
mqtt:
  sensor:
    - name: "cv_flame"
      state_topic: "events/central_heating/otmonitor/flame"
      value_template: "{{ value_json.value }}"
    - name: "cv_hotwater"
      state_topic: "events/central_heating/otmonitor/hotwater"
      value_template: "{{ value_json.value }}"
    - name: "cv_centralheating"
      state_topic: "events/central_heating/otmonitor/centralheating"
      value_template: "{{ value_json.value }}"
etc.

So I can view Opentherm data on a dashboard.

Hope this will clarify my setup.

**Comment by Alexwijn** [comment]
Unfortunately that isn't supported. This component is designed to work together with: https://github.com/rvdbreemen/OTGW-firmware.

**Comment by hhoef** [comment]
Maybe I can make a mqtt translation? What mqtt structure is SAT expecting?

Groetjes uit Delft

**Comment by Alexwijn** [comment]
There would be a lot of things you would need to expose, and it also needs the ability to send commands, otherwise it can't change the setpoint for example.

**Comment by sergeantd83** [comment]
Or you can create a new connection type that will connect to OTGW through OTMonitor. You can have the `mqtt` connection as example.
