### ISSUE TITLE
Usage with ebusd mqtt possible?

### ISSUE THREAD

**Issue by bayc4d** [Alexwijn/SAT#32]
Hi i have a ebus adapter i use with SetModeOverride option because i cant sync config files with my boiler.

i want to modulation or pid for energy saving. 

Is it possible to use ebusd with sat?

**Comment by sergeantd83** [comment]
Currently we support only OpenTherm connection through OTGW, because we own OpenTherm boilers. But if anyone would like to bring SAT in the EBUS world we will be more than happy. SAT modular nature can handle this.

**Comment by kapryk** [comment]
The idea for the SAT is universal. It checks the internal and external temperature, calculates CS, and the user (e.g. using automation) sends the CS value to the boiler or mixing valve

**Comment by andreid1303** [comment]
Also I would like to use SAT integration for controlling boiler flow temp via Ebus. For this setup I only need output to custom input_number helper and using custom sensors in HA. Is it possible?
