### ISSUE TITLE
integrate minimum control setpoint, or detect a start 

### ISSUE THREAD

**Issue by AOskam** [Alexwijn/SAT#35]
Hi, 

Cool integration, running into an issue however. 
My gas heater has difficulties modulating so low it can sustain a low control setpoint. even when all TRV's and underfloor heating have heating demand. 

if i start the SAT, it controls the setpoint to low, resulting in the gas heater starting to cycle on and off constantly, because it cannot reduce power quick enough so ctrl setpoint is exceeded. Resulting in this behaviour. An temporary higher setpoint for the first couple of minutes or a minimum setpoint setting would fix this. 

regards

**Comment by sergeantd83** [comment]
It looks that SAT had some issues regarding calculating the `overshoot_protection` value during initial configuration. If you tried the `Calibrate and determine your overshoot protection value (approx. 20 min)` option during the initial configuration and this proccess lasted way less time than 20 min then this value is wrong. You can perform a manual calculation of the `overshoot_protection_value` using this [guide](https://github.com/Alexwijn/SAT/discussions/36).

>if i start the SAT, it controls the setpoint to low, resulting in the gas heater starting to cycle on and off constantly, because it cannot reduce power quick enough so ctrl setpoint is exceeded. Resulting in this behaviour. An temporary higher setpoint for the first couple of minutes or a minimum setpoint setting would fix this.

You describe the low-load control that is already implemented in SAT. If you want some more in depth help you are welcome to join the SAT dedicated [Discord server](https://discord.gg/97dcgzAexR).

Regards
