### ISSUE TITLE
Calibrating does not end

### ISSUE THREAD

**Issue by HMvdZijden** [Alexwijn/SAT#38]
During setup and automatic calibrating (20 minutes) the calibrating stucks.

**Comment by Alexwijn** [comment]
Please define stuck. How long has he been trying to calibrate and did you monitor your setpoint and actual temperature?

**Comment by HMvdZijden** [comment]
The popup stays for hours telling it might take 20 minutes and when you close the popup there is no device. I did not monitor anything. The boiler is somewhat old, it is a remeha avanta 28c and it does not support many ot commands.

**Comment by HMvdZijden** [comment]
I had to remove the integration. With manual setting the boiler does not start anymore.

**Comment by HMvdZijden** [comment]
It is a pity.
