### ISSUE TITLE
Configuring a multi-zone setup with custom heat pump controls?

### ISSUE THREAD

**Issue by joostmeijles** [Alexwijn/SAT#48]
I have a multi-zone underfloor setup which is controlled by 3 Danfoss Icon controllers.
With in total 7 zones which each have their own thermostat. The Danfoss Icon master can only send an on/off heat signal to my heat pump.  This is not desired as it will result in many start/stops. 

As a result I now have a situation where my heat pump runs in weather dependent mode, where it keeps the water at a certain temperature. And the Danfoss controllers open valves for a zone when heat is required.
This is a suboptimal set up which I would like to improve and wonder if SAT can help.

I can control the setpoint temperature and on/off for my heat pump via MQTT.
The 7 Danfoss thermostats are also available via MQTT.

So I am thinking to use SAT to get to an optimised situation where SAT:
- reads the thermostat values
- calculates the setpoint (and on/off signal)
- send the setpoint and on/off signal

Is this a viable setup using SAT?

**Comment by sergeantd83** [comment]
Hi, do your heat pump support OpenTherm? How you change the setpoint temperature and control the on/off of the pump?

**Comment by joostmeijles** [comment]
Hey, yes I think it does. I have a Daikin Altherma 3 heat pump.

Currently I can control it (setpoint / on-off) via MQTT by using
https://github.com/Arnold-n/P1P2MQTT

Op zo 13 okt 2024 om 20:35 schreef sergeantd83 ***@***.***>

**Comment by sergeantd83** [comment]
> Currently I can control it (setpoint / on-off) via MQTT by using
https://github.com/Arnold-n/P1P2MQTT

Currently we don’t support the P1P2 bus connection.

Are you sure that your boiler has OpenTherm terminals and you can hook an OpenTherm thermostat?

**Comment by joostmeijles** [comment]
> Are you sure that your boiler has OpenTherm terminals and you can hook an OpenTherm thermostat?
Not sure, it actually seems not to support OpenTherm :(.

> Currently we don’t support the P1P2 bus connection.
Not sure about the complexity to implement this based on the MQTT controls. I would be happy to create a PR for it if you can provide some guidance.

**Comment by sergeantd83** [comment]
Maybe it is better to move the discussion to our discord server, since we need to do some extensive research on bringing support to P1P2 bus connection. https://discord.gg/jnVXpzqGEq
