### ISSUE TITLE
Make controlling child climates optional

### ISSUE THREAD

**Issue by clau-bucur** [Alexwijn/SAT#57]
Currently SAT is operating 4 of my climate entities.
Those climates also have "a mind of their own" regarding their `hvac_mode`. An individual climate is turned off by automations when the window in that room is opened, for example. And more use cases.
I do not want to use SAT's integrated window detection feature because my automations are working nicely and cover more cases.

I have for example another use case, where I suspend the heating system until a set date (using an `input.date_time`). The SAT climate entity is automatically turned off while the heating is suspended. This now turns off my child climates.
I do not desire for the child climates to turn off because it messes up with other automations and trigger heating watchdogs.

What would be nice instead to have in SAT, is a controllable switch entity which instructs SAT to not change the `hvac_mode` of the child climate entities when that "controllable switch entity is on".

So the switch should be a part of the "Controls" section of the SAT device.
![image](https://github.com/user-attachments/assets/449b8a64-8c7a-4ad6-b294-44f8ae21c761)

**Why a switch entity and not a config flow configuration setting?**
Because the switch can be automated based on different scenarios. The config flow configuration setting is static configuration and one needs to reconfigure SAT in order to change the behavior.

**Comment by enryIT** [comment]
Don't set your child climates as main climates in SAT, put them in the "rooms" section.

**Comment by clau-bucur** [comment]
That's what I did and experienced the reported behavior.
![image](https://github.com/user-attachments/assets/a082c067-9b78-4f15-bf39-857fd5eec709)

**Comment by enryIT** [comment]
I really don't know why this happens, on my instance SAT doesn't control child "rooms" climates, it simply checks if at least one is in `heating` state or not before starting the burner.

Are you using an old version of SAT? Have you tries using the latest development version?

**Comment by clau-bucur** [comment]
Yes, I'm running the latest development version from a couple weeks ago -- it has ESPHome support included which I'm using.

Well, looking at the code it's pretty obvious it controls both main and room (secondary as they're called in the config flow) climates.
`climate.py` line 940:
```
for entity_id in (self._climates + self._main_climates):
     data = {ATTR_ENTITY_ID: entity_id, ATTR_HVAC_MODE: hvac_mode}
     await self.hass.services.async_call(CLIMATE_DOMAIN, SERVICE_SET_HVAC_MODE, data, blocking=True)
```
Here the room climates are `self._climates`.

**Comment by enryIT** [comment]
Oh I'm sorry, you also wrote that before but I just realized you're talking about simply the HVAC mode and not the actual temperatures set on those climates.

You are right then, just take out `self._climates` from that line, or since you don't even use the main climate just leave all commented as you already did.

Also, please note that @Alexwijn has just committed some changes you'll like ;)
https://github.com/Alexwijn/SAT/commit/e319ac4193eaaffba5df95732c299e1192c80514

**Comment by Alexwijn** [comment]
You're welcome 😉

**Comment by clau-bucur** [comment]
Thanks alot @Alexwijn! I'm installing the latest develop version and give it a try.
