### ISSUE TITLE
What thermostat is in control?

### ISSUE THREAD

**Issue by iiLaurens** [Alexwijn/SAT#62]
So I am slightly confused about this. My primary concern is the WAF (wife approval factor), so please read this post from that perspective.

We have a thermostat on the wall (honeywell round). So this is what is used to request a temperature by the family. Can I still use SAT or does SAT assume it is controlled directly via Home Assistant and ignore all other thermostats? Will the two thermostats be in conflict? Or will SAT observe the requested setpoint on the physical thermostat and control the boiler from there?

**Comment by sergeantd83** [comment]
If this is your [issue](https://community.home-assistant.io/t/custom-component-smart-autotune-thermostat/550542/62),
then that is your [answer](https://community.home-assistant.io/t/custom-component-smart-autotune-thermostat/550542/66)😉

**Comment by iiLaurens** [comment]
I had quite the chuckle whilst reading that. WAF determines everything!

Seems like I'm not alone in this, so wouldn't it make sense to have this an option in SAT directly for optimal support?
