### ISSUE TITLE
Can't setup dev version using esphome

### ISSUE THREAD

**Issue by tbrasser** [Alexwijn/SAT#63]
Modified my esphome yaml to the SAT expected naming. However can't setup the integration:

```
File "/config/custom_components/sat/config_flow.py", line 339, in async_step_calibrate device_name = self.config_entry.data.get(CONF_NAME) ^^^^^^^^^^^^^^^^^^^^^^ 
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by Alexwijn** [comment]
Which Home Assistant are you running, and how did you set up SAT?

**Comment by tbrasser** [comment]
I got a bit further, after not choosing autocalibrate I could add the config entry.

Now it's stuck in autocalibration after I chose 'reconfigure':

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Bron: custom_components/sat/climate.py:684
integratie: Smart Autotune Thermostat (documentatie, problemen)
Eerst voorgekomen: 13:46:39 (370 gebeurtenissen)
Laatst gelogd: 14:35:19

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/sat/climate.py", line 684, in _async_climate_changed
    self._rooms[new_state.entity_id] = float(target_temperature)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
```

**Comment by tbrasser** [comment]
I removed my fake living room thermostat and configured only the rooms. Seems things are working now.

I'm on the latest development branch commit (updated a few times yesterday)

So my Remeha Condensing boiler setpoint and max relative modulation are controlled now! Nice

Would you recommend lowering the max power on the boiler directly (like I did from 35 to 25kW) or let SAT work with the full 35kW (it calculates correctly either way since opentherm communicates back what the max power is at 100% rel mod)
